/**
 * 系统事件
 */

// 刷新首页的列表美食爱心
const REFRESH_INDEX_MEISHI_LIST = "REFRESH_INDEX_MEISHI_LIST";
const REFRESH_VIPRECOM_MEISHI_LIST = "REFRESH_VIPRECOM_MEISHI_LIST";

// 登录选择网点返回
// const LOGIN_CHOOSE_ORG_SUCCESS = "LOGIN_CHOOSE_ORG_SUCCESS";
// 刷新我的路线列表
const REFRESH_GENERAL_ROAD_LIST = "REFRESH_GENERAL_ROAD_LIST";


export default {
	REFRESH_INDEX_MEISHI_LIST: REFRESH_INDEX_MEISHI_LIST,
	REFRESH_VIPRECOM_MEISHI_LIST: REFRESH_VIPRECOM_MEISHI_LIST,
	REFRESH_GENERAL_ROAD_LIST: REFRESH_GENERAL_ROAD_LIST
}
